spring:
  application:
    name: movies-info-service
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: admin
      password: password
      database: test
server:
  port: 8100
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2

api:
  resource: movies
  name: ${spring.application.name}
  version: 1.0.0